matches:
  # Standard UUID.
  - trigger: ":uuid"
    replace: "{{uuid}}"
    propagate_case: true
    uppercase_style: uppercase
    vars:
      - name: uuid
        type: script
        params:
          args:
            - python3
            - -c
            - |
              import uuid
              print(str(uuid.uuid4()))

  # Non-dashed UUID.
  - trigger: ":nuuid"
    replace: "{{uuid_nodash}}"
    propagate_case: true
    uppercase_style: uppercase
    vars:
      - name: uuid_nodash
        type: script
        params:
          args:
            - python3
            - -c
            - |
              import uuid
              print(str(uuid.uuid4()).replace('-', ''))